# Generated by Django 5.0.7 on 2025-10-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminDashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Manager", "Manager"),
                    ("Employee", "Employee"),
                ],
                default="Employee",
                max_length=16,
            ),
        ),
    ]
