# Generated by Django 5.0.7 on 2025-10-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminDashboard", "0002_alter_profile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="vacation_days",
            field=models.IntegerField(default=20),
        ),
    ]
