# Generated by Django 5.2 on 2025-09-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myDesk", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="approved",
            field=models.BooleanField(),
        ),
    ]
