# Generated by Django 5.2 on 2025-08-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myDesk", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Admin", "Admin"),
                    ("Manager", "Manager"),
                    ("Employee", "Employee"),
                ],
                null=True,
            ),
        ),
    ]
