# Generated by Django 5.2 on 2025-09-06 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myDesk", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="employement_date",
            new_name="employment_date",
        ),
    ]
