# Generated by Django 5.2 on 2025-09-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myDesk", "0002_alter_request_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="request",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
