# Generated by Django 5.2 on 2025-09-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myDesk", "0003_request_processed_alter_request_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="manager_message",
            field=models.TextField(blank=True),
        ),
    ]
